# SW 1 

# Aufgabenteil I

In [61]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import palmerpenguins

In [62]:
df_penguins = sns.load_dataset("penguins")
df_penguins.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

### Aufgabe 1 & 2: Wie viele Beobachtungen & Merkmale gibt es? Welche Variablen gibt es?

In [63]:
df_penguins.info()
df_penguins.describe()
print("Anzahl Beobachtungen:", df_penguins.shape[0])
print("Anzahl Merkmale:", df_penguins.shape[1])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB
Anzahl Beobachtungen: 344
Anzahl Merkmale: 7

### Aufgabe 3: Was bedeuten diese Variablen? In welchen Einheiten wurden sie gemessen?

In [64]:
for i in df_penguins.columns:
    if len(i.split("_")) == 3:
        display(i.split("_")[0] + ":" + i.split("_")[1] + "[" + i.split("_")[2] + "]")
    elif len(i.split("_")) == 2:
        display(i.split("_")[0] + ":" + i.split("_")[1])
    else:
        display(i.split("_")[0])

'species'

'island'

'bill:length[mm]'

'bill:depth[mm]'

'flipper:length[mm]'

'body:mass[g]'

'sex'

In [65]:
print(palmerpenguins.__doc__) ##gibt die Dokumentation des Pakets aus, findet aber leider nichts.

None

We could check the website itself for more info on data: [Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/)

### Aufgabe 4: Welche Merkmalstypen & Datentypen haben die Variablen?

In [66]:
df_penguins.info() ## gives information about data types, what is object though?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [70]:
df_penguins.head() 
display(df_penguins[df_penguins.isna().any(axis=1)])

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN
246,Gentoo,Biscoe,44.5,14.3,216.0,4100.0,NaN
286,Gentoo,Biscoe,46.2,14.4,214.0,4650.0,NaN
324,Gentoo,Biscoe,47.3,13.8,216.0,4725.0,NaN
336,Gentoo,Biscoe,44.5,15.7,217.0,4875.0,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN

In [ ]:
for i in df_penguins.columns[[0,1,6]]:
    print(i + ":", df_penguins[i].unique()) ## gives the unique values of each column, but not for the numerical ones.
print("or")

for i in ["species","island","sex"]:
    print(i + ":", df_penguins[i].unique()) ## this does the same as the previous one, but only for the categorical columns.

species: ['Adelie' 'Chinstrap' 'Gentoo']
island: ['Torgersen' 'Biscoe' 'Dream']
sex: ['Male' 'Female' nan]
or
species: ['Adelie' 'Chinstrap' 'Gentoo']
island: ['Torgersen' 'Biscoe' 'Dream']
sex: ['Male' 'Female' nan]

## Aufgabenteil II

Fragen: 
- sind species unique auf einer insel? 
- zeigen einzelnen species signifikant unterschiedliche Messwerte des Schnabels / der Flossen / des Körpergewichts? 
- sind diese Messwerte bei Weibchen statistisch grösser oder kleiner als bei Männchen? 
- ...